### ISSUE TITLE
update downwith.us/hexelgram

### ISSUE THREAD

**Issue by jennschiffer** [dysphasia/hexelgram#1]
for fuck's sake Nick, I know it's like "the fourth of july" or something but let's keep our heads in the game ok friend?

**Comment by dysphasia** [comment]
What do you mean???

On Thursday, July 4, 2013, Jenn wrote:

> for fuck's sake Nick, I know it's like "the fourth of july" or something
> but let's keep our heads in the game ok friend?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/youbastard/hexelgram/issues/1
> .

## 

Nicholas Ortenzio
nicholas.ortenzio@gmail.com

**Comment by jennschiffer** [comment]
on the live page it has the number field for pixel size, but I just cloned the repo to my machine and it has a slider

**Comment by jennschiffer** [comment]
for real though, happy fourth of july. I hope you got to see some parades and hot dogs

**Comment by dysphasia** [comment]
Oh lol I was trying to program and then my brother showed up and made me
leave my apartment. Now I'm in JC with jen

On Thursday, July 4, 2013, Jenn wrote:

> for real though, happy fourth of july. I hope you got to see some parades
> and hot dogs
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/youbastard/hexelgram/issues/1#issuecomment-20495027
> .

## 

Nicholas Ortenzio
nicholas.ortenzio@gmail.com

**Comment by jennschiffer** [comment]
Hahaha brothers, man. Have fun with ya grrrl!
